/**
 * NyayaSetu — Consultation Status Constants
 * Mirrors backend ConsultationStatus enum exactly.
 */

export const CONSULTATION_STATUS = {
  REQUESTED:         'REQUESTED',
  REVIEWING:         'REVIEWING',
  ACCEPTED:          'ACCEPTED',
  SCHEDULED:         'SCHEDULED',
  PAYMENT_PENDING:   'PAYMENT_PENDING',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  MEET_LINK_ADDED:   'MEET_LINK_ADDED',
  READY:             'READY',
  IN_PROGRESS:       'IN_PROGRESS',
  COMPLETED:         'COMPLETED',
  // Terminal — negative
  REJECTED:          'REJECTED',
  CANCELLED:         'CANCELLED',
  NO_SHOW:           'NO_SHOW',
};

export const STATUS_LABELS = {
  [CONSULTATION_STATUS.REQUESTED]:         'Requested',
  [CONSULTATION_STATUS.REVIEWING]:         'Under Review',
  [CONSULTATION_STATUS.ACCEPTED]:          'Accepted',
  [CONSULTATION_STATUS.SCHEDULED]:         'Scheduled',
  [CONSULTATION_STATUS.PAYMENT_PENDING]:   'Payment Pending',
  [CONSULTATION_STATUS.PAYMENT_CONFIRMED]: 'Payment Confirmed',
  [CONSULTATION_STATUS.MEET_LINK_ADDED]:   'Meet Link Added',
  [CONSULTATION_STATUS.READY]:             'Ready to Join',
  [CONSULTATION_STATUS.IN_PROGRESS]:       'In Progress',
  [CONSULTATION_STATUS.COMPLETED]:         'Completed',
  [CONSULTATION_STATUS.REJECTED]:          'Rejected',
  [CONSULTATION_STATUS.CANCELLED]:         'Cancelled',
  [CONSULTATION_STATUS.NO_SHOW]:           'No Show',
};

export const STATUS_CSS_CLASS = {
  [CONSULTATION_STATUS.REQUESTED]:         'badge-requested',
  [CONSULTATION_STATUS.REVIEWING]:         'badge-pending',
  [CONSULTATION_STATUS.ACCEPTED]:          'badge-accepted',
  [CONSULTATION_STATUS.SCHEDULED]:         'badge-scheduled',
  [CONSULTATION_STATUS.PAYMENT_PENDING]:   'badge-pending',
  [CONSULTATION_STATUS.PAYMENT_CONFIRMED]: 'badge-accepted',
  [CONSULTATION_STATUS.MEET_LINK_ADDED]:   'badge-accepted',
  [CONSULTATION_STATUS.READY]:             'badge-accepted',
  [CONSULTATION_STATUS.IN_PROGRESS]:       'badge-scheduled',
  [CONSULTATION_STATUS.COMPLETED]:         'badge-completed',
  [CONSULTATION_STATUS.REJECTED]:          'badge-rejected',
  [CONSULTATION_STATUS.CANCELLED]:         'badge-rejected',
  [CONSULTATION_STATUS.NO_SHOW]:           'badge-rejected',
};

/** Valid next statuses for a given current status (lawyer actions) */
export const VALID_TRANSITIONS = {
  [CONSULTATION_STATUS.REQUESTED]:         [CONSULTATION_STATUS.REVIEWING, CONSULTATION_STATUS.REJECTED],
  [CONSULTATION_STATUS.REVIEWING]:         [CONSULTATION_STATUS.ACCEPTED, CONSULTATION_STATUS.REJECTED],
  [CONSULTATION_STATUS.ACCEPTED]:          [CONSULTATION_STATUS.SCHEDULED],
  [CONSULTATION_STATUS.SCHEDULED]:         [CONSULTATION_STATUS.PAYMENT_PENDING],
  [CONSULTATION_STATUS.PAYMENT_PENDING]:   [CONSULTATION_STATUS.PAYMENT_CONFIRMED, CONSULTATION_STATUS.CANCELLED],
  [CONSULTATION_STATUS.PAYMENT_CONFIRMED]: [CONSULTATION_STATUS.MEET_LINK_ADDED],
  [CONSULTATION_STATUS.MEET_LINK_ADDED]:   [CONSULTATION_STATUS.READY],
  [CONSULTATION_STATUS.READY]:             [CONSULTATION_STATUS.IN_PROGRESS],
  [CONSULTATION_STATUS.IN_PROGRESS]:       [CONSULTATION_STATUS.COMPLETED, CONSULTATION_STATUS.NO_SHOW],
};
